#!/usr/bin/env python3
"""
Generate .wordpress-org/icon.svg, icon-128x128.png, icon-256x256.png, icon-512x512.png
(one-time, static – not regenerated by the workflow).
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import math

OUT_DIR = Path(__file__).parent.parent / '.wordpress-org'
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ── SVG (resolution-independent) ─────────────────────────────────────────────
SVG = '''\
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%"   stop-color="#ff9900"/>
      <stop offset="100%" stop-color="#cc7a00"/>
    </linearGradient>
  </defs>

  <!-- Background rounded square -->
  <rect width="512" height="512" rx="96" ry="96" fill="url(#bg)"/>

  <!-- Cloud body -->
  <g fill="#1d2327">
    <!-- main body -->
    <rect x="112" y="248" width="288" height="112" rx="20"/>
    <!-- left bump -->
    <circle cx="176" cy="240" r="64"/>
    <!-- centre bump -->
    <circle cx="256" cy="208" r="80"/>
    <!-- right bump -->
    <circle cx="336" cy="232" r="56"/>
  </g>

  <!-- "WP" initials below cloud -->
  <text x="256" y="430"
        font-family="DejaVu Sans, Arial, sans-serif"
        font-size="72"
        font-weight="bold"
        text-anchor="middle"
        fill="#1d2327"
        letter-spacing="4">WP</text>
</svg>
'''

svg_path = OUT_DIR / 'icon.svg'
svg_path.write_text(SVG)
print(f'Saved {svg_path}')


# ── PNG rasteriser ────────────────────────────────────────────────────────────
def cloud_icon(size):
    """Draw the icon at the given square pixel size using Pillow."""
    img  = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    s    = size / 512  # scale factor

    # Background: rounded square with orange gradient approximated as flat fill
    r = int(96 * s)
    draw.rounded_rectangle([0, 0, size - 1, size - 1], radius=r, fill='#ff9900')

    # Slightly darker border
    draw.rounded_rectangle([0, 0, size - 1, size - 1], radius=r,
                            outline='#cc7a00', width=max(1, int(4 * s)))

    # ── Cloud shape ───────────────────────────────────────────────────────────
    cloud_col = '#1d2327'

    # Main body rectangle
    bx1, by1 = int(112 * s), int(248 * s)
    bx2, by2 = int(400 * s), int(360 * s)
    draw.rounded_rectangle([bx1, by1, bx2, by2], radius=int(20 * s), fill=cloud_col)

    # Three bumps (circles) on top
    for cx, cy, cr in [(176, 240, 64), (256, 208, 80), (336, 232, 56)]:
        cx_, cy_, cr_ = int(cx * s), int(cy * s), int(cr * s)
        draw.ellipse([cx_ - cr_, cy_ - cr_, cx_ + cr_, cy_ + cr_], fill=cloud_col)

    # ── "WP" text ─────────────────────────────────────────────────────────────
    try:
        f = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
                               int(72 * s))
    except OSError:
        f = ImageFont.load_default()

    text = 'WP'
    bbox = draw.textbbox((0, 0), text, font=f)
    tw   = bbox[2] - bbox[0]
    tx   = (size - tw) // 2
    ty   = int(370 * s)
    draw.text((tx, ty), text, font=f, fill='#1d2327')

    return img


for px in (128, 256, 512):
    icon = cloud_icon(px)
    out  = OUT_DIR / f'icon-{px}x{px}.png'
    icon.save(out)
    print(f'Saved {out}')
